export const students = [
    {
        surname: 'Антонов',
        name: 'Павел',
        age: 16,
        faculty: 'Безопасность телекоммуникационных систем',
        course: 1,
        score: 4.2,
    },
    {
        surname: 'Веревкин',
        name: 'Алексей',
        age: 17,
        faculty: 'Сети и системы связи',
        course: 2,
        score: 3.8,
    },
    {
        surname: 'Сухова',
        name: 'Тамара',
        age: 17,
        faculty: 'Оптико-волоконные системы',
        course: 2,
        score: 4.8,
    },
    {
        surname: 'Андреев',
        name: 'Андрей',
        age: 17,
        faculty: 'Оптико-волоконные системы',
        course: 2,
        score: 3.7,
    },
    {
        surname: 'Белова',
        name: 'Екатерина',
        age: 18,
        faculty: 'Безопасность телекоммуникационных систем',
        course: 3,
        score: 4.9,
    },
    {
        surname: 'Григорьев',
        name: 'Дмитрий',
        age: 19,
        faculty: 'Сети и системы связи',
        course: 4,
        score: 4.1,
    },
    {
        surname: 'Денисова',
        name: 'Анна',
        age: 16,
        faculty: 'Оптико-волоконные системы',
        course: 1,
        score: 4.5,
    },
    {
        surname: 'Егоров',
        name: 'Сергей',
        age: 18,
        faculty: 'Безопасность телекоммуникационных систем',
        course: 3,
        score: 3.5,
    },
    {
        surname: 'Жукова',
        name: 'Ольга',
        age: 17,
        faculty: 'Сети и системы связи',
        course: 2,
        score: 4.7,
    },
    {
        surname: 'Зайцев',
        name: 'Иван',
        age: 19,
        faculty: 'Оптико-волоконные системы',
        course: 4,
        score: 3.9,
    },
    {
        surname: 'Иванова',
        name: 'Мария',
        age: 16,
        faculty: 'Сети и системы связи',
        course: 1,
        score: 4.3,
    },
    {
        surname: 'Козлов',
        name: 'Николай',
        age: 18,
        faculty: 'Безопасность телекоммуникационных систем',
        course: 3,
        score: 3.6,
    },
    {
        surname: 'Лебедева',
        name: 'Светлана',
        age: 17,
        faculty: 'Оптико-волоконные системы',
        course: 2,
        score: 4.4,
    },
    {
        surname: 'Михайлов',
        name: 'Александр',
        age: 19,
        faculty: 'Сети и системы связи',
        course: 4,
        score: 4.0,
    },
    {
        surname: 'Новикова',
        name: 'Елена',
        age: 16,
        faculty: 'Безопасность телекоммуникационных систем',
        course: 1,
        score: 4.6,
    },
    {
        surname: 'Новикова',
        name: 'Светлана',
        age: 16,
        faculty: 'Безопасность телекоммуникационных систем',
        course: 1,
        score: 4.8,
    },
];
